/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mclaren_mp45__formula_1.glb 
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-mp45-formula-1-3059d4532ecd48ca8da41e1cac971f22
Title: McLaren MP4/5 || Formula 1
*/

import React, { useMemo, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import * as THREE from "three";



export function Mclaren(props) {
  const { nodes, materials } = useGLTF('./models/mclaren_mp45__formula_1.glb')
  const platicMaterial = useMemo (() => new THREE.MeshBasicMaterial({
    color: "blue"
  }), [])

  // MeshStandar reflects light adds detail in exchange of it being a more resource hungry type of material
  const standarPlasticMaterial = useMemo(() => new THREE.MeshStandardMaterial({
    color: "red",          // Change color as needed
    roughness: 0.4,        // Slightly rough to simulate plastic
    metalness: 0,          // No metallic properties
    transparent: false, 
  }))

  const selectedMaterial = standarPlasticMaterial;

  return (
    <group {...props} dispose={null} name="Mclaren">
      <group position={[0, -0.319, 0]} name="wheels and botom">
        <group position={[0, 0.319, 0]}>
          <mesh geometry={nodes.Object_7.geometry} material={selectedMaterial} />
        </group>

        <group position={[0, 0.319, 0]}>
          <group position={[0, 0.734, 0.908]}>
            <mesh geometry={nodes.Object_18.geometry} material={selectedMaterial} />         
          </group>

          <mesh geometry={nodes.Object_12.geometry} material={selectedMaterial} />
          <mesh geometry={nodes.Object_13.geometry} material={selectedMaterial} />
        </group>

        <mesh geometry={nodes.Object_4.geometry} material={selectedMaterial} />
        
        <mesh geometry={nodes.Object_10.geometry} material={selectedMaterial} position={[0, 0.829, -2.749]} /> {/*backwheels */}
        <mesh geometry={nodes.Object_25.geometry} material={selectedMaterial} position={[0, 0.319, 0]} />
        <mesh geometry={nodes.Object_27.geometry} material={selectedMaterial} position={[0, 0.789, 2.056]} /> {/*/frontwheels */}
      </group>
    </group>
  )
}

useGLTF.preload('./models/mclaren_mp45__formula_1.glb')
